repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1 # https://github.com/pre-commit/pre-commit-hooks/tags
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: end-of-file-fixer

# reorder imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports

# consistent code formatting
-   repo: https://github.com/psf/black
    rev: 21.7b0 # https://github.com/psf/black/tags
    hooks:
    -   id: black
        name: Black (code formatting)
        language_version: python3

# linting
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2 # https://gitlab.com/pycqa/flake8/-/tags
    hooks:
    -   id: flake8
        name: Flake8 (linting)
        additional_dependencies: [flake8-bugbear, flake8-docstrings]
        exclude: ^src/nspyre/gui/

# static type-checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        name: MyPy (type-checking)
        exclude: ^src/nspyre/gui/|^tests/fixtures/drivers/

# build docs
- repo: local
  hooks:
    -   id: sphinx
        name: Sphinx (docs)
        entry: bash -c 'make -C docs clean && make -C docs html'
        language: system
        types: [python]
        pass_filenames: false
