repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # https://github.com/pre-commit/pre-commit-hooks/tags
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: destroyed-symlinks

# reorder imports
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.4
    hooks:
    -   id: reorder-python-imports

# consistent code formatting
-   repo: https://github.com/psf/black
    rev: 22.10.0 # https://github.com/psf/black/tags
    hooks:
    -   id: black
        name: Black (code formatting)
        language_version: python3

# linting
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2 # https://gitlab.com/pycqa/flake8/-/tags
    hooks:
    -   id: flake8
        name: Flake8 (linting)
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

# static type-checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        name: MyPy (type-checking)
        exclude: ^tests/fixtures/drivers/|^src/nspyre/gui/instrument_manager.py

# build docs
- repo: local
  hooks:
    -   id: sphinx
        name: Sphinx (docs)
        entry: make -C docs html
        language: system
        pass_filenames: false
